version: "3"
services:
  backend:
    restart: always
    hostname: backend
    env_file:
      - ./backend/.env
    ports:
      - 3000:3000
      - 9229:9229
    build: backend/.
    volumes:
      - ./backend:/usr/src/app
  db:
    image: mariadb
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
